import type {Metadata} from 'next'
import {Geist, Geist_Mono} from 'next/font/google'
import './globals.css'
import Header from '@/components/layout/header'
import Footer from "@/components/layout/Footer";
import Sidebar from "@/components/layout/sidebar";

const geistSans = Geist({
    variable: '--font-geist-sans',
    subsets: ['latin'],
})

const geistMono = Geist_Mono({
    variable: '--font-geist-mono',
    subsets: ['latin'],
})

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode
}>) {
    return (
        <html lang="en">
        <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
            <Header/>
            <main className="flex gap-8 p-8 flex-col md:flex-row">
                {children}
                <Sidebar/>
            </main>
            <Footer/>
        </body>
        </html>
    )
}
